region               = "us-east-1"
bucket_name          = "my-unique-terraform-demo-bucket-12345" # must be globally unique
instance_type        = "t3.micro"
key_name             = "my-existing-keypair"
db_name              = "demo_db"
db_username          = "admin"
db_password          = "Admin1234!"
lambda_function_name = "demo-lambda"
lambda_filename      = "lambda/lambda.zip" # create this zip before apply
event_rule_name      = "daily-lambda-trigger"
event_schedule_expr  = "rate(1 day)"
